include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

stages:
  - lint
  - test

lint:
  stage: lint
  image: denoland/deno:alpine
  script:
    - deno lint --unstable

test:
  stage: test
  image: denoland/deno:alpine
  script:
    - deno test --coverage=cov --unstable
    - deno coverage cov --lcov --output=lcov.info
    - deno run --allow-read --allow-write https://deno.land/x/lcov_cobertura/mod.ts lcov.info -o coverage.xml
    - deno run --allow-read https://deno.land/x/code_coverage@0.2.1/cli.ts
  coverage: /Totals:.*?\d+\.\d+\%/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
